//! Compiled protobuf types and gRPC service definitions for the
//! Agent Nervous System.
//!
//! This crate re-exports the generated code from `proto/ans.proto`.
//! All other crates depend on this one for the gRPC contract.

#![deny(unsafe_code, rust_2018_idioms)]
#![allow(missing_docs, unused_imports)]

/// Module containing all generated proto types.
///
/// Generated by `tonic_build` from `proto/ans.proto`.
/// The package name in the proto file is `ans`, so tonic
/// generates an `ans` module with all message types and
/// the gRPC service client/server.
#[allow(clippy::all, clippy::pedantic, clippy::nursery, clippy::cargo)]
pub mod ans {
    tonic::include_proto!("ans");
}
