# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ans_pb2 as ans__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ans_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentNervousSystemStub(object):
    """────────────────────────────────────────────────────────────
    Agent Nervous System — Complete gRPC Service Definition
    Version: 1.0.0 (Phase 0 — Protocols Frozen)
    ────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/ans.AgentNervousSystem/CreateSession',
                request_serializer=ans__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=ans__pb2.Session.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/ans.AgentNervousSystem/CloseSession',
                request_serializer=ans__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=ans__pb2.Empty.FromString,
                _registered_method=True)
        self.Navigate = channel.unary_unary(
                '/ans.AgentNervousSystem/Navigate',
                request_serializer=ans__pb2.NavigateRequest.SerializeToString,
                response_deserializer=ans__pb2.PageState.FromString,
                _registered_method=True)
        self.ExecuteAction = channel.unary_unary(
                '/ans.AgentNervousSystem/ExecuteAction',
                request_serializer=ans__pb2.ExecuteActionRequest.SerializeToString,
                response_deserializer=ans__pb2.ActionResult.FromString,
                _registered_method=True)
        self.GetDistilledDom = channel.unary_unary(
                '/ans.AgentNervousSystem/GetDistilledDom',
                request_serializer=ans__pb2.DomRequest.SerializeToString,
                response_deserializer=ans__pb2.DistilledDom.FromString,
                _registered_method=True)
        self.CaptureScreenshot = channel.unary_unary(
                '/ans.AgentNervousSystem/CaptureScreenshot',
                request_serializer=ans__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=ans__pb2.ScreenshotResponse.FromString,
                _registered_method=True)
        self.ComputeDiff = channel.unary_unary(
                '/ans.AgentNervousSystem/ComputeDiff',
                request_serializer=ans__pb2.DiffRequest.SerializeToString,
                response_deserializer=ans__pb2.DiffReport.FromString,
                _registered_method=True)
        self.CreateGoal = channel.unary_unary(
                '/ans.AgentNervousSystem/CreateGoal',
                request_serializer=ans__pb2.CreateGoalRequest.SerializeToString,
                response_deserializer=ans__pb2.GoalState.FromString,
                _registered_method=True)
        self.GetGoalState = channel.unary_unary(
                '/ans.AgentNervousSystem/GetGoalState',
                request_serializer=ans__pb2.GoalStateRequest.SerializeToString,
                response_deserializer=ans__pb2.GoalState.FromString,
                _registered_method=True)
        self.UpdateGoalProgress = channel.unary_unary(
                '/ans.AgentNervousSystem/UpdateGoalProgress',
                request_serializer=ans__pb2.ProgressUpdate.SerializeToString,
                response_deserializer=ans__pb2.GoalState.FromString,
                _registered_method=True)
        self.SubscribeGoalUpdates = channel.unary_stream(
                '/ans.AgentNervousSystem/SubscribeGoalUpdates',
                request_serializer=ans__pb2.GoalStateRequest.SerializeToString,
                response_deserializer=ans__pb2.GoalUpdate.FromString,
                _registered_method=True)
        self.SubmitEyeReports = channel.unary_unary(
                '/ans.AgentNervousSystem/SubmitEyeReports',
                request_serializer=ans__pb2.SubmitReportsRequest.SerializeToString,
                response_deserializer=ans__pb2.RoutedSignal.FromString,
                _registered_method=True)
        self.SubscribeEyeReports = channel.unary_stream(
                '/ans.AgentNervousSystem/SubscribeEyeReports',
                request_serializer=ans__pb2.SessionRequest.SerializeToString,
                response_deserializer=ans__pb2.EyeReport.FromString,
                _registered_method=True)
        self.ClassifyDistractions = channel.unary_unary(
                '/ans.AgentNervousSystem/ClassifyDistractions',
                request_serializer=ans__pb2.DistractionRequest.SerializeToString,
                response_deserializer=ans__pb2.DistractionList.FromString,
                _registered_method=True)
        self.ScanInjections = channel.unary_unary(
                '/ans.AgentNervousSystem/ScanInjections',
                request_serializer=ans__pb2.InjectionScanRequest.SerializeToString,
                response_deserializer=ans__pb2.InjectionScanResult.FromString,
                _registered_method=True)
        self.CheckAction = channel.unary_unary(
                '/ans.AgentNervousSystem/CheckAction',
                request_serializer=ans__pb2.ActionCheckRequest.SerializeToString,
                response_deserializer=ans__pb2.ActionCheckResponse.FromString,
                _registered_method=True)
        self.StoreScore = channel.unary_unary(
                '/ans.AgentNervousSystem/StoreScore',
                request_serializer=ans__pb2.StoreScoreRequest.SerializeToString,
                response_deserializer=ans__pb2.StoreScoreResponse.FromString,
                _registered_method=True)
        self.QueryBestActions = channel.unary_unary(
                '/ans.AgentNervousSystem/QueryBestActions',
                request_serializer=ans__pb2.QueryBestActionsRequest.SerializeToString,
                response_deserializer=ans__pb2.ScoredActionList.FromString,
                _registered_method=True)
        self.SearchSimilarDecisions = channel.unary_unary(
                '/ans.AgentNervousSystem/SearchSimilarDecisions',
                request_serializer=ans__pb2.SearchRequest.SerializeToString,
                response_deserializer=ans__pb2.ScoredActionList.FromString,
                _registered_method=True)
        self.GetBudgetStatus = channel.unary_unary(
                '/ans.AgentNervousSystem/GetBudgetStatus',
                request_serializer=ans__pb2.BudgetStatusRequest.SerializeToString,
                response_deserializer=ans__pb2.BudgetStatus.FromString,
                _registered_method=True)
        self.ConfigureBudget = channel.unary_unary(
                '/ans.AgentNervousSystem/ConfigureBudget',
                request_serializer=ans__pb2.BudgetConfigRequest.SerializeToString,
                response_deserializer=ans__pb2.BudgetConfig.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/ans.AgentNervousSystem/Health',
                request_serializer=ans__pb2.Empty.SerializeToString,
                response_deserializer=ans__pb2.HealthStatus.FromString,
                _registered_method=True)


class AgentNervousSystemServicer(object):
    """────────────────────────────────────────────────────────────
    Agent Nervous System — Complete gRPC Service Definition
    Version: 1.0.0 (Phase 0 — Protocols Frozen)
    ────────────────────────────────────────────────────────────

    """

    def CreateSession(self, request, context):
        """── Session Management ──────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Navigate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDistilledDom(self, request, context):
        """── Perception ──────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureScreenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeDiff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGoal(self, request, context):
        """── Goal State ──────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGoalState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGoalProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeGoalUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitEyeReports(self, request, context):
        """── Eye Reports (Streaming) ─────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEyeReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyDistractions(self, request, context):
        """── Immune System ───────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanInjections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreScore(self, request, context):
        """── Decision Intelligence ───────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryBestActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSimilarDecisions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBudgetStatus(self, request, context):
        """── Budget ──────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """── Health ──────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentNervousSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=ans__pb2.CreateSessionRequest.FromString,
                    response_serializer=ans__pb2.Session.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=ans__pb2.CloseSessionRequest.FromString,
                    response_serializer=ans__pb2.Empty.SerializeToString,
            ),
            'Navigate': grpc.unary_unary_rpc_method_handler(
                    servicer.Navigate,
                    request_deserializer=ans__pb2.NavigateRequest.FromString,
                    response_serializer=ans__pb2.PageState.SerializeToString,
            ),
            'ExecuteAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=ans__pb2.ExecuteActionRequest.FromString,
                    response_serializer=ans__pb2.ActionResult.SerializeToString,
            ),
            'GetDistilledDom': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDistilledDom,
                    request_deserializer=ans__pb2.DomRequest.FromString,
                    response_serializer=ans__pb2.DistilledDom.SerializeToString,
            ),
            'CaptureScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureScreenshot,
                    request_deserializer=ans__pb2.ScreenshotRequest.FromString,
                    response_serializer=ans__pb2.ScreenshotResponse.SerializeToString,
            ),
            'ComputeDiff': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeDiff,
                    request_deserializer=ans__pb2.DiffRequest.FromString,
                    response_serializer=ans__pb2.DiffReport.SerializeToString,
            ),
            'CreateGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGoal,
                    request_deserializer=ans__pb2.CreateGoalRequest.FromString,
                    response_serializer=ans__pb2.GoalState.SerializeToString,
            ),
            'GetGoalState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGoalState,
                    request_deserializer=ans__pb2.GoalStateRequest.FromString,
                    response_serializer=ans__pb2.GoalState.SerializeToString,
            ),
            'UpdateGoalProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGoalProgress,
                    request_deserializer=ans__pb2.ProgressUpdate.FromString,
                    response_serializer=ans__pb2.GoalState.SerializeToString,
            ),
            'SubscribeGoalUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeGoalUpdates,
                    request_deserializer=ans__pb2.GoalStateRequest.FromString,
                    response_serializer=ans__pb2.GoalUpdate.SerializeToString,
            ),
            'SubmitEyeReports': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitEyeReports,
                    request_deserializer=ans__pb2.SubmitReportsRequest.FromString,
                    response_serializer=ans__pb2.RoutedSignal.SerializeToString,
            ),
            'SubscribeEyeReports': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEyeReports,
                    request_deserializer=ans__pb2.SessionRequest.FromString,
                    response_serializer=ans__pb2.EyeReport.SerializeToString,
            ),
            'ClassifyDistractions': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyDistractions,
                    request_deserializer=ans__pb2.DistractionRequest.FromString,
                    response_serializer=ans__pb2.DistractionList.SerializeToString,
            ),
            'ScanInjections': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanInjections,
                    request_deserializer=ans__pb2.InjectionScanRequest.FromString,
                    response_serializer=ans__pb2.InjectionScanResult.SerializeToString,
            ),
            'CheckAction': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAction,
                    request_deserializer=ans__pb2.ActionCheckRequest.FromString,
                    response_serializer=ans__pb2.ActionCheckResponse.SerializeToString,
            ),
            'StoreScore': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreScore,
                    request_deserializer=ans__pb2.StoreScoreRequest.FromString,
                    response_serializer=ans__pb2.StoreScoreResponse.SerializeToString,
            ),
            'QueryBestActions': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryBestActions,
                    request_deserializer=ans__pb2.QueryBestActionsRequest.FromString,
                    response_serializer=ans__pb2.ScoredActionList.SerializeToString,
            ),
            'SearchSimilarDecisions': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSimilarDecisions,
                    request_deserializer=ans__pb2.SearchRequest.FromString,
                    response_serializer=ans__pb2.ScoredActionList.SerializeToString,
            ),
            'GetBudgetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBudgetStatus,
                    request_deserializer=ans__pb2.BudgetStatusRequest.FromString,
                    response_serializer=ans__pb2.BudgetStatus.SerializeToString,
            ),
            'ConfigureBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureBudget,
                    request_deserializer=ans__pb2.BudgetConfigRequest.FromString,
                    response_serializer=ans__pb2.BudgetConfig.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ans__pb2.Empty.FromString,
                    response_serializer=ans__pb2.HealthStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ans.AgentNervousSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ans.AgentNervousSystem', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentNervousSystem(object):
    """────────────────────────────────────────────────────────────
    Agent Nervous System — Complete gRPC Service Definition
    Version: 1.0.0 (Phase 0 — Protocols Frozen)
    ────────────────────────────────────────────────────────────

    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/CreateSession',
            ans__pb2.CreateSessionRequest.SerializeToString,
            ans__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/CloseSession',
            ans__pb2.CloseSessionRequest.SerializeToString,
            ans__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Navigate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/Navigate',
            ans__pb2.NavigateRequest.SerializeToString,
            ans__pb2.PageState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/ExecuteAction',
            ans__pb2.ExecuteActionRequest.SerializeToString,
            ans__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDistilledDom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/GetDistilledDom',
            ans__pb2.DomRequest.SerializeToString,
            ans__pb2.DistilledDom.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/CaptureScreenshot',
            ans__pb2.ScreenshotRequest.SerializeToString,
            ans__pb2.ScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeDiff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/ComputeDiff',
            ans__pb2.DiffRequest.SerializeToString,
            ans__pb2.DiffReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/CreateGoal',
            ans__pb2.CreateGoalRequest.SerializeToString,
            ans__pb2.GoalState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGoalState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/GetGoalState',
            ans__pb2.GoalStateRequest.SerializeToString,
            ans__pb2.GoalState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGoalProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/UpdateGoalProgress',
            ans__pb2.ProgressUpdate.SerializeToString,
            ans__pb2.GoalState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeGoalUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ans.AgentNervousSystem/SubscribeGoalUpdates',
            ans__pb2.GoalStateRequest.SerializeToString,
            ans__pb2.GoalUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitEyeReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/SubmitEyeReports',
            ans__pb2.SubmitReportsRequest.SerializeToString,
            ans__pb2.RoutedSignal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEyeReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ans.AgentNervousSystem/SubscribeEyeReports',
            ans__pb2.SessionRequest.SerializeToString,
            ans__pb2.EyeReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyDistractions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/ClassifyDistractions',
            ans__pb2.DistractionRequest.SerializeToString,
            ans__pb2.DistractionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanInjections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/ScanInjections',
            ans__pb2.InjectionScanRequest.SerializeToString,
            ans__pb2.InjectionScanResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/CheckAction',
            ans__pb2.ActionCheckRequest.SerializeToString,
            ans__pb2.ActionCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/StoreScore',
            ans__pb2.StoreScoreRequest.SerializeToString,
            ans__pb2.StoreScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryBestActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/QueryBestActions',
            ans__pb2.QueryBestActionsRequest.SerializeToString,
            ans__pb2.ScoredActionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSimilarDecisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/SearchSimilarDecisions',
            ans__pb2.SearchRequest.SerializeToString,
            ans__pb2.ScoredActionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBudgetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/GetBudgetStatus',
            ans__pb2.BudgetStatusRequest.SerializeToString,
            ans__pb2.BudgetStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/ConfigureBudget',
            ans__pb2.BudgetConfigRequest.SerializeToString,
            ans__pb2.BudgetConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ans.AgentNervousSystem/Health',
            ans__pb2.Empty.SerializeToString,
            ans__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
